### ISSUE TITLE
How do I modify the style of the line in drag and drop？

### ISSUE THREAD

**Issue by itWorkergg** [raisezhang/react-drag-listview#36]
dragProps = {
    onDragEnd: this.moveRow,
    handleSelector: 'i',
    lineClassName: 'borderBottom: 2px dashed deepskyblue !important'
  }; is error，How do I write it correctly？thank you

**Comment by raisezhang** [comment]
Css class name: 

``` css
.global-drag-line {
  border-color: green!important;
}
```

How to use：

``` javascript
const dragProps = {
  onDragEnd: this.moveRow,
  handleSelector: 'i',
  lineClassName: 'global-drag-line',
};
```

Example：https://codepen.io/raisezhang/pen/BaNveMp
